---
title: "Lac_phylogeny"
author: "Bosco Gracia Alvira"
date: "2024-10-16"
output: html_document
---

```{r Load libraries}

# Standard table management
library(data.table) ; packageVersion("data.table")
library(tidyverse) ; packageVersion("tidyverse")
library(readr) ; packageVersion("readr")
library(dplyr) ; packageVersion("dplyr")

# Hierarchical clustering 
library(pvclust) ; packageVersion("pvclust")

# Phylogenetic tree visualisation
library(treeio) ; packageVersion("treeio")
library(ggtree) ; packageVersion("ggtree")
library(phytools) ; packageVersion("phytools")

# Advanced dendrograms visualisation
library(dendextend) ; packageVersion("dendextend")

#
#library(ggdendro) ; packageVersion("ggdendro")
#library(patchwork) ; packageVersion("patchwork")
#library(ape) ; packageVersion("ape")
#library(vegan) ; packageVersion("vegan")
#library(RColorBrewer) ; packageVersion("RColorBrewer")

```

```{r Set paths}

tree_path <- "/Users/bgracia/PopGen Dropbox/Martin McFly/Bosco/PhD_Dropbox/Microbiome_pangenomic_analysis/data/Lactiplantibacillus_plantarum/Phylogeny/snp-sites/Lpla.phylip.treefile"
pan_path <- "/Users/bgracia/PopGen Dropbox/Martin McFly/Bosco/PhD_Dropbox/Microbiome_pangenomic_analysis/data/Lactiplantibacillus_plantarum/Phylogeny/roary/gene_presence_absence.Rtab"
metadata_path <- "/Users/bgracia/PopGen Dropbox/Martin McFly/Bosco/PhD_Dropbox/Microbiome_pangenomic_analysis/data/Lactiplantibacillus_plantarum/Phylogeny/metadata.tsv"
visuals_path <- "/Users/bgracia/PopGen Dropbox/Martin McFly/Bosco/PhD_Dropbox/Microbiome_pangenomic_analysis/visuals"

```

```{r Phylogenetic tree}
  
# Load the metadata file and set the Strains as key
metadata <- fread(metadata_path)
row.names(metadata) <- metadata$Strain
setkey(metadata, Strain)

# Load the representative genomes tree based on core genome SNPs
tree <- read.tree(tree_path)
tree <- ladderize(tree, right = FALSE)

# Remove the .fa suffix from the tip labels
tree$tip.label <- sub("\\.fa$", "", tree$tip.label)

# Modify the outgroup tip label
tree$tip.label[tree$tip.label == "Lpla_ref.gbff.fna"] <- "Reference"

# Re-root the tree to the outgroup
new_root_node <- which(tree$tip.label == "NIZO2776")

# Re-root the tree to the midpoint between the outgroup and the rest of the tree
tree <- midpoint.root(tree, node.labels=new_root_node)

# Build the tree plot with bootstrap values and metadata
tree_plot <- ggtree(tree, size = 0.3) %<+% metadata + 
                  geom_tippoint(aes(color = Source), size = 0.5) +
                  geom_tiplab(aes(color = Source), size = 2, align = TRUE) +
                  geom_text2(aes(subset = !isTip, label = label), hjust = 1.2, vjust = -0.5, size = 2) +
                  scale_color_manual(values = setNames(metadata$Colour, metadata$Source)) +
                  theme_tree2() +
                  scale_y_continuous(expand = c(0.05, 0.20))  # Adjust the expand parameter as needed

tree_plot

ggsave(filename = "Lac_phylogeny.png", plot = tree_plot, path = visuals_path, width = 20, height = 10, dpi = 300)

```


```{r Functional tree}

# Select our isolates, except for the representatives from each strain
hot <- metadata %>% filter(Source == "HOT") %>% select(Strain) %>% filter(Strain != "S239")
base <- metadata %>% filter(Source == "BASE") %>% select(Strain) %>% filter(Strain != "B89")
cold <- metadata %>% filter(Source %in% c("COLD", "COLD-CONSTANT")) %>% select(Strain) %>% filter(Strain != "S103")
remove_cols <- c(hot$Strain, cold$Strain, base$Strain)

# Load the genes presence-absence matrix and set the gene names as row names
pan <- read.table(pan_path, header = TRUE, check.names = FALSE)
row.names(pan) <- pan$Gene
pan <- pan %>% select(-Gene) %>% select(-one_of(remove_cols))

# Transpose the data so that rows are genomes and columns are genes
tpan <- as.data.frame(t(pan))
tpan$Strain <- row.names(tpan)
tpan <- tpan %>%
  semi_join(metadata, by = "Strain")
tpan <- tpan %>% select(-Strain)

# Calculate the binary distances between the samples
dist_pan <- dist(tpan, method = "binary")

# Perform hierarchical clustering with bootstrap on the distance matrix using pvclust
set.seed(999)
pvclust_result <- pvclust(as.matrix(dist_pan), parallel = as.integer(10), method.hclust = "ward.D", nboot = 1000)

# Extract dendrogram data and bootstrap values
dendro_pan <- as.dendrogram(pvclust_result)
bootstrap_values <- pvclust_result[["edges"]][["au"]][order.dendrogram(dendro_pan)]

#Colour the labels based on the source of isolation, and bootstraps based on significance
label_colors <- metadata$Colour[match(labels(dendro_pan), metadata$Strain)]
node_colors <- ifelse(bootstrap_values > 0.90, "red", "black")
node_sizes <- ifelse(bootstrap_values > 0.90, 0.5, 0.01)

# Modify the dendrogram to include the coloured labels
dendro_pan_2 <- dendro_pan %>%
  #assign_values_to_nodes_nodePar(19, nodePar="pch") %>%
  #set("nodes_cex", node_sizes) %>%
  #assign_values_to_nodes_nodePar(node_colors, nodePar="col") %>%
  set("labels_colors", label_colors)

dendro_pan_2 %>% plot()

png(filename = paste0(visuals_path,"/Lac_dendrogram.png"), width = 4000, height = 2000, res = 300)
dendro_pan_2 %>% plot()
pvclust_result %>% text(col=c(au=2, bp="transparent", edge="transparent"), print.num=FALSE, float=0.01, cex=0.5)
dev.off()

####################

# Transpose the data so that rows are genomes and columns are genes
tpan <- as.data.frame(t(pan))

# Perform hierarchical clustering of the binary distances between genomes
dist_pan <- dist(tpan, method = "binary")
hclust_pan <- hclust(dist_pan, method = "ward.D")

# Convert hclust object to dendrogram
dendro_pan <- as.dendrogram(hclust_pan)

# Make a metadata file in which the rows are sorted as in the dendrogram
# This will be needed to match the colours to the correct labels
metadata_pan <- metadata[J(labels(dendro_pan))]

# Extract the colors from the reordered metadata
# Assign colors to the dendrogram labels
dendro_cols <- as.character(metadata_pan$Colour)
labels_colors(dendro_pan) <- dendro_cols

# Convert the dendrogram to a ggdend object
ggdendro_pan <- as.ggdend(dendro_pan)

# Create a ggplot object for the dendrogram
dendro_plot <- ggplot() +
  geom_segment(data = ggdendro_pan$segments, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_point(data = ggdendro_pan$labels, aes(x = x, y = y), size = 2) +
  #geom_text(data = ggdendro_pan$labels, aes(x = x, y = y, label = label, color = dendro_cols), angle = 90, hjust = 1, size = 3) +
  scale_color_identity() +
  theme_classic() +
  coord_flip() +
  #scale_y_reverse() +
  scale_x_reverse() +
  labs(title = "Functional clustering of the isolates", y = "Binary distance", x = "Isolate")

dendro_plot

# Save the plot using ggsave
ggsave(filename = "Lac_dendrogram.png", plot = dendro_plot, path = visuals_path, width = 20, height = 10, dpi = 300)

```



```{r Functional ordination}
# Hierarchical clustering is okay, but I prefer PCAs :)
# We can use the same presence/absence table

# Calculate PCA of the presence/absence pattern
pca_pan <- prcomp(tpan, retx = T)

# Pick the coordinates from the PCA and save it in a new data frame
# Include the strain name
pca_data <- as.data.frame(pca_pan$x)
pca_data$Strain <- rownames(pca_data)

# How much variance is explained by each PC? 
# This is the square of the standard deviations divided by the total variance.
sdev <- pca_pan$sdev
variance_explained <- sdev^2 / sum(sdev^2)
percentage_variance_explained <- variance_explained * 100

# We merge each genome's coordinates and metadata
# We set a vector with the colours that we want for each isolation source
pca_merged <- merge(pca_data, metadata, by="Strain")
color_vector <- setNames(pca_merged$Colour, pca_merged$Source)

# We plot PC1vsPC2 and PC4vsPC5, we are not interested in PC3, plot it if you want though
pca12 <- ggplot(pca_merged, aes(x = PC1, y = PC2, colour = Source)) +
              geom_point(size = 3, alpha=0.5) +
              #geom_text(aes(label = genome), color = "black") +
              theme_minimal() +
              scale_colour_manual(values = color_vector) +
              labs(title = "Isolates PCA based on genes presence/absence",
                   x = paste0("PC1 (", round(percentage_variance_explained[1], 2), "% variance)"),
                   y = paste0("PC2 (", round(percentage_variance_explained[2], 2), "% variance)"),
                   color = "Source of isolation")

pca12

ggsave(filename = "Lac_PCA12.png", plot = pca12, path = visuals_path, width = 10, height = 6, dpi = 300)


pca45 <- ggplot(pca_merged, aes(x = PC4, y = PC5, colour = Source)) +
              geom_point(size = 3, alpha=0.5) +
              #geom_text(aes(label = genome), color = "black") +
              theme_minimal() +
              scale_colour_manual(values = color_vector) +
              labs(title = "Isolates PCA based on genes presence/absence",
                   x = paste0("PC4 (", round(percentage_variance_explained[4], 2), "% variance)"),
                   y = paste0("PC5 (", round(percentage_variance_explained[5], 2), "% variance)"),
                   color = "Source of isolation")

pca45

ggsave(filename = "Lac_PCA45.png", plot = pca45, path = visuals_path, width = 10, height = 6, dpi = 300)

```


```{r Combine the tree and dendrogram}

# Extract labels and coordinates from tree_plot and dendro_plot
phylo_labels <- tree_plot$data$label
phylo_labels <- na.omit(phylo_labels)
dendro_labels <- ggdendro_pan$labels$label

# Create the link_data data frame
link_data <- data.frame(
  phylo_x = rep(max(tree_plot$data$x, na.rm = TRUE), length(phylo_labels)),
  phylo_y = tree_plot$data$y[match(phylo_labels, tree_plot$data$label)],
  dendro_x = rep(min(ggdendro_pan$labels$x, na.rm = TRUE), length(dendro_labels)),
  dendro_y = ggdendro_pan$labels$y[match(dendro_labels, ggdendro_pan$labels$label)]
)

# Check for any NA values in link_data
if (any(is.na(link_data))) {
  warning("There are NA values in link_data. Please check the labels and data.")
}

# Combine the plots using patchwork and add linking segments
combined_plot <- tree_plot + 
  geom_segment(data = link_data, aes(x = phylo_x, y = phylo_y, xend = dendro_x, yend = dendro_y), color = "grey") +
  dendro_plot + 
  plot_layout(ncol = 1)

# Set the output file path
output_file <- file.path(visuals_path, "combined_plot.png")

# Save the combined plot using ggsave
#ggsave(output_file, plot = combined_plot, width = 15, height = 16, dpi = 300)


```
